### PR TITLE
Update dependencies and optimize dockerfile

### PR DESCRIPTION
**Pull request by rogersachan**
This pull request does the following:
* Update `gulp-connect`, `http-proxy-middleware`, `angular`, and `@uirouter/angularjs` to the latest versions.
  * `angular-ui-router` became `@uirouter/angularjs`
* Reflect support for yarn in README
* Remove hacks I used in the dockerfile to get npm and bower (e.g. installing git) to work by using yarn instead, which is shipped in the base image.

### CODE REVIEW

**Comment by segler-alex** [comment]
hi, thank you for your help.
does yarn work for you? when i do a
$ yarn
it always stops with the following error
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
warning gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > graceful-fs > natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
error Couldn't find package "interpret@^1.0.0" required by "gulp@^3.9.1" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "liftoff@^2.1.0" required by "gulp@^3.9.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:237:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:266:123)
    at PackageRequest.<anonymous> (/usr/share/yarn/lib/cli.js:36410:17)
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:98:30)
    at /usr/share/yarn/lib/cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by segler-alex** [comment]
when i do
$ npm install
it just works

**Comment by rogersachan** [comment]
It works for me on PC and docker so far, and I'll leave my log here for reference. Are you having this error consistently?

```
05/10 03:23 AM (40m)
Step 1/6 : FROM node:alpine
05/10 03:23 AM (40m)
 ---> 3036d4c4fcea
05/10 03:23 AM (40m)
Step 2/6 : ADD . /root
05/10 03:23 AM (40m)
 ---> 66566cf36945
05/10 03:23 AM (40m)
Step 3/6 : WORKDIR /root
05/10 03:23 AM (40m)
 ---> fa82fd20a443
05/10 03:23 AM (40m)
Removing intermediate container c56013ffd57d
05/10 03:23 AM (40m)
Step 4/6 : RUN yarn global add gulp &&     yarn
05/10 03:23 AM (40m)
 ---> Running in cbe9bd0ddf98
05/10 03:23 AM (40m)
yarn global v1.6.0
05/10 03:23 AM (40m)
(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
05/10 03:23 AM (40m)
[1/4] Resolving packages...
05/10 03:23 AM (40m)
warning gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > graceful-fs > natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
05/10 03:23 AM (40m)
[2/4] Fetching packages...
05/10 03:23 AM (40m)
[3/4] Linking dependencies...
05/10 03:23 AM (40m)
[4/4] Building fresh packages...
05/10 03:23 AM (40m)
success Installed "gulp@3.9.1" with binaries:
05/10 03:23 AM (40m)
      - gulp
05/10 03:23 AM (40m)
Done in 2.52s.
05/10 03:23 AM (40m)
yarn install v1.6.0
05/10 03:23 AM (40m)
(node:28) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
05/10 03:23 AM (40m)
info No lockfile found.
05/10 03:23 AM (40m)
[1/4] Resolving packages...
05/10 03:23 AM (40m)
warning gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > graceful-fs > natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
05/10 03:23 AM (40m)
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
05/10 03:23 AM (40m)
[2/4] Fetching packages...
05/10 03:23 AM (40m)
[3/4] Linking dependencies...
05/10 03:23 AM (40m)
[4/4] Building fresh packages...
05/10 03:23 AM (40m)
success Saved lockfile.
05/10 03:23 AM (40m)
Done in 3.58s.
05/10 03:23 AM (40m)
 ---> fbcd4e7bc5e6
05/10 03:23 AM (40m)
Removing intermediate container cbe9bd0ddf98
05/10 03:23 AM (40m)
Step 5/6 : EXPOSE 4200
05/10 03:23 AM (40m)
 ---> Running in bd6aa2c0cee9
05/10 03:23 AM (40m)
 ---> 3e1e06e2713e
05/10 03:23 AM (40m)
Removing intermediate container bd6aa2c0cee9
05/10 03:23 AM (40m)
Step 6/6 : CMD gulp
05/10 03:23 AM (40m)
 ---> Running in 7673c4a32d06
05/10 03:23 AM (40m)
 ---> efd69bf04043
05/10 03:23 AM (40m)
Removing intermediate container 7673c4a32d06
05/10 03:23 AM (40m)
Successfully built efd69bf04043
05/10 03:23 AM (40m)
Successfully tagged registry.now.systems/now/a5c3a240d40c7616b0a1b4f86bfbb0dae8d964af:latest
05/10 03:23 AM (40m)
exit code: 0
05/10 03:23 AM (40m)
Storing image
05/10 03:23 AM (40m)
Deploying image
05/10 03:23 AM (40m)
Container started
05/10 03:23 AM (40m)
[07:23:54] Using gulpfile ~/gulpfile.js
05/10 03:23 AM (40m)
[07:23:54] Starting 'connect'...
05/10 03:23 AM (40m)
[07:23:54] Starting server...
05/10 03:23 AM (40m)
[HPM] Proxy created: /webservice  ->  http://www.radio-browser.info
05/10 03:23 AM (40m)
[07:23:54] Finished 'connect' after 12 ms
05/10 03:23 AM (40m)
[07:23:54] Starting 'watch'...
05/10 03:23 AM (40m)
[07:23:54] Finished 'watch' after 24 ms
05/10 03:23 AM (40m)
[07:23:54] Starting 'default'...
05/10 03:23 AM (40m)
[07:23:54] Finished 'default' after 36 μs
05/10 03:23 AM (40m)
[07:23:54] Server started http://0.0.0.0:4200
05/10 03:23 AM (40m)
[07:23:54] LiveReload started on port 35729
05/10 03:23 AM (40m)
[07:23:54] Running server
```

**Comment by segler-alex** [comment]
i have it constantly and even when i do
$ docker build .
:(

**Comment by rogersachan** [comment]
What version of node and yarn are you using?

**Comment by rogersachan** [comment]
Maybe run `npm config set registry https://registry.npmjs.org/` before trying it?

**Pull request merged**
