### PR TITLE
Add Async functions to Index.HTML to reduce page load time.

### PR DESCRIPTION
**Pull request by ZeroDot1**
I think if you load all the scripts and the Css Asyncron the loading time is better.
This update is especially important for all the users who have slow internet e.g. me.

### CODE REVIEW

**Comment by ZeroDot1** [comment]
Here is a demo screenshot, I think it looks much better now.
bildschirmfoto vom 2019-01-23 15-56-31

**Comment by ZeroDot1** [comment]
@segler-alex Please have a look at the updates I have made.
I would be happy to see the updates in the future live on the radio browser page, because I think they are good improvements for the project.

**Comment by ZeroDot1** [comment]
@segler-alex,
Here is a CSS snippet for buttons in yellow, if you like it you can use it for RadioBrowser.
bildschirmfoto vom 2019-01-23 16-31-04

```css
button {
  color: black !important;
 background-image: linear-gradient(#FFF0A8, #F9B421);
 border: 1px solid #FF9933;
 display: inline-block;
 padding: .5em 1em;
 margin-bottom: 0;
 font-weight: 400;
 line-height: 1.2;
 text-align: center;
 white-space: nowrap;
 vertical-align: middle;
 cursor: pointer;
 border: 1px solid transparent;
 border-radius: .2em;
 text-decoration: none;
 box-shadow: 0 0 5px #333;
}
```

**Comment by segler-alex** [comment]
thank you

**Comment by ZeroDot1** [comment]
If you have questions please let me know, I hope the improvements are all ok.

**Comment by segler-alex** [comment]
please do not provide code in the comments. make a pull request. i will accept if you do not break stuff. i am gratefull for every design improvement

**Pull request merged**
